name: 'pagila_analytics'
version: '1.0.0'
config-version: 2

profile: 'pagila_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pagila_analytics:
    staging:
      +materialized: view
      pagila:
        +schema: staging_pagila
      sakila:
        +schema: staging_sakila
    intermediate:
      +materialized: table
      pagila:
        +schema: intermediate_pagila
      sakila:
        +schema: intermediate_sakila
    marts:
      +materialized: table
      +schema: marts
    analytics:
      +materialized: table
      +schema: analytics